-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 13:22:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS db_projeto DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE db_projeto;

-- Tabela: usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id_usuarios INT AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha CHAR(60) NOT NULL,
  PRIMARY KEY (id_usuarios),
  UNIQUE INDEX email_UNIQUE (email)
) ENGINE = InnoDB;

-- Tabela: categorias
CREATE TABLE IF NOT EXISTS categorias (
  id_categorias INT AUTO_INCREMENT,
  nome_categoria VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_categorias),
  UNIQUE INDEX nome_categoria_UNIQUE (nome_categoria)
) ENGINE = InnoDB;

-- Tabela: mesas
CREATE TABLE IF NOT EXISTS mesas (
  id_mesas INT AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT,
  id_categoria INT,
  id_organizador INT,
  localizacao VARCHAR(150),
  numero_jogadores TINYINT NOT NULL DEFAULT 1,
  nivel_experiencia ENUM('Iniciante', 'Intermediário', 'Avançado') NOT NULL,
  sistema_regras VARCHAR(100) NOT NULL,
  tipo_campanha ENUM('one-shot', 'campanha longa') NOT NULL,
  disponibilidade TINYINT DEFAULT 1,
  status ENUM('ativa', 'excluída') DEFAULT 'ativa',
  PRIMARY KEY (id_mesas),
  CONSTRAINT fk_mesas_categoria
    FOREIGN KEY (id_categoria)
    REFERENCES categorias (id_categorias)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_mesas_organizador
    FOREIGN KEY (id_organizador)
    REFERENCES usuarios (id_usuarios)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Tabela: participacoes
CREATE TABLE IF NOT EXISTS participacoes (
  id_participacoes INT AUTO_INCREMENT,
  id_usuario INT NOT NULL,
  id_mesa INT NOT NULL,
  status ENUM('pendente', 'aceito', 'recusado') DEFAULT 'pendente',
  PRIMARY KEY (id_participacoes),
  CONSTRAINT fk_participacoes_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios (id_usuarios)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_participacoes_mesa
    FOREIGN KEY (id_mesa)
    REFERENCES mesas (id_mesas)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Tabela: avaliacoes
CREATE TABLE IF NOT EXISTS avaliacoes (
  id_avaliacao INT AUTO_INCREMENT,
  id_usuario INT NOT NULL,
  id_mesa INT NOT NULL,
  nota TINYINT NOT NULL,
  comentario TEXT,
  PRIMARY KEY (id_avaliacao),
  CONSTRAINT fk_avaliacoes_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios (id_usuarios)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_avaliacoes_mesa
    FOREIGN KEY (id_mesa)
    REFERENCES mesas (id_mesas)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Tabela: favoritos
CREATE TABLE IF NOT EXISTS favoritos (
  id_favorito INT AUTO_INCREMENT,
  id_usuario INT NOT NULL,
  id_mesa INT NOT NULL,
  PRIMARY KEY (id_favorito),
  CONSTRAINT fk_favoritos_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios (id_usuarios)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_favoritos_mesa
    FOREIGN KEY (id_mesa)
    REFERENCES mesas (id_mesas)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;